language: php

php:
   - 7.0
   - 7.1
   - nightly

sudo: false

branches:
   only:
      - master

notifications:
   email: true

install:
   - composer install --no-dev --quiet

script: phpunit -c phpunit.xml --coverage-text