language: php

php:
   - 7.0
   - 7.1
   - hhvm
   - nightly

sudo: false

cache:
   directories:
      - node_modules
      - vendor

branches:
   only:
      - master

notifications:
   email: false

install:
   - composer install --no-dev --quiet

script: phpunit -c phpunit.xml --coverage-text

before_script:
   - curl -sSf -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar