language: php
php:
- 7.0
- 7.1
sudo: false
cache:
  directories:
  #- vendor
branches:
  only:
  - master
notifications:
  email: true
before_script:
- composer install
script: vendor/bin/phpunit -c phpunit.xml