language: php

php:
   - 7.0
   - 7.1
   - nightly

sudo: false

cache:
   directories:
      - vendor

branches:
   only:
      - master

notifications:
   email: true

install:
   - composer install --quiet

script: phpunit -c phpunit.xml --coverage-text